### ISSUE TITLE
mmenu - article / Probleme mit mehreren Seitenbäumen

### ISSUE THREAD

**Issue by traumwerk** [dklemmt/contao_dk_mmenu#13]
Ich setze vielmals das mmenu - article ein, da ich jeweils noch andere Contents/Links ins Flyout nehme. Passt auch perfekt für einen Seitenbaum.
Jedoch bei mehreren Seitenbäumen tritt das Problem auf, dass ich jeweils den Artikel den ich anziehen will, nur aus dem 1. resp. obersten Seitenbaum auswählen kann.
Das heisst habe ich zwei oder mehrere Bäume, müsste ich die Artikel im ersten Seitenbaum platzieren, ist da aber ein wenig unglücklich, da es sich ja um zwei Eigenständige Bäume handelt... dasselbe bei mehrsprachigen Webseiten.

Beispiel eines Inhaltelementes mit Zugriff auf alle Seitenbäume:
Artikel (Include Elemente) > Bezogener Artikel 
(Bei der Auswahl kann man Artikel aus allen Seitenbäumen auswählen)

**Comment by fritzmg** [comment]
In der neuesten Version wurde dieses Modul entfernt. Stattdessen kann man nun beliebigen HTML Code einfügen - auch Insert Tags natürlich. Ich würde empfehlen zB [contao-node](https://github.com/terminal42/contao-node) zu verwenden (je nach Anwendungsfall).
