### ISSUE TITLE
Contao 4 Kompatibilität

### ISSUE THREAD

**Issue by Schooott** [dklemmt/contao_dk_mmenu#14]
Hi,

ist eine Version für Contao 4.x in naher Zukunft geplant?

**Comment by redwise** [comment]
Hallo Herr Klemmt, 

leider kommt einen Fehlermeldung bei Verwendung Ihrer tollen Extension.

Hier die Fehlermeldung ( TypeError: $mmenu.mmenu is not a function])

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Fehler/Not_a_function

Vielen Dank für Ihre Hilfe...

**Comment by Jaaaan** [comment]
Dem schließe ich mich an. Eine Freigabe für Contao 4.4 wäre ideal, da die Erweiterung bereits im neuen Contao Manager zur Verfügung steht, jedoch die Installation aufgrund fehlender Freigabe immer fehl schlägt.

**Comment by rustykowski** [comment]
Danke für die Freigabe!

**Comment by fritzmg** [comment]
See https://github.com/dklemmt/contao_dk_mmenu/releases/tag/2.0.0
