### ISSUE TITLE
Error: click on anchor navigation does not close the menu

### ISSUE THREAD

**Issue by jankout** [dklemmt/contao_dk_mmenu#16]
When I use your extension for my anchor navigation the click does not close the menu. I think this is an  error. Can you fix it, please, or write me how I can fix it by myself. Thank you. 

Here is the website where I use it. http://dev.akupunkturpunkt.com/

**Comment by fritzmg** [comment]
Does this still happen in version 2.0.0?

**Comment by rorych** [comment]
In my case it is not working as long as you have a webpage in front of the hashtag.
If you only have the hashtag it seems to work, but for a navigation i think the

example.php#test -> Scrolls to #test, navi still open
#test -> Scrolls to #test, navi closes

Could that be or is that only my installation?

**Comment by fritzmg** [comment]
Does this issue only occur with this extension or also when you integrate _mmenu_ manually? If the latter is the case, then you need to report it here instead: https://github.com/FrDH/jQuery.mmenu/issues

**Comment by rorych** [comment]
I'm not shure, i will have to test. Thanks for the input, i didn't notice how this is connected to mmenu.

**Comment by fritzmg** [comment]
The extension has been rewritten and updated. Please try again and re-open this ticket if necessary.
