### ISSUE TITLE
4.4.x compatibility 

### ISSUE THREAD

**Issue by jankout** [dklemmt/contao_dk_mmenu#19]
Hello Dirk, 

it would be great to use your extension with 4.4.x Contao version. Could you update the dependencies, please? Thank you. 

Best wishes, Jan

**Comment by designpilot** [comment]
Hallo Dirk

Deine Erweiterung wird im Contao Manager angezeigt, die Installation schlägt dann aber fehl weil diese für die 4.4.* leider noch nicht freigegeben ist (ich bin gezwungen die Erweiterungen über die Console zu installieren, da die WebGUI Ausführung leider nur 256MB Ram erlaubt).

Kannst Du bitte die Erweiterung freigeben, damit man diese über die Console (für diejenigen die sie über diese installieren müssen) installieren kann.

Danke im Voraus
Didier

**Comment by Jaaaan** [comment]
Über 'dev-master' sollte es schon jetzt funktionieren.
Dazu das Einstellungsrad nutzen.

**Comment by designpilot** [comment]
Hi Jaaaan

Oder in der Console mit php7.1-cli contao-manager.phar.php composer require dklemmt/dk_mmenu:dev-master installieren oder ????

**Comment by fritzmg** [comment]
See https://github.com/dklemmt/contao_dk_mmenu/pull/21
