### ISSUE TITLE
mmenu - Artikel

### ISSUE THREAD

**Issue by redwise** [dklemmt/contao_dk_mmenu#2]
Hallo,

es kann ja im Modultyp ein mmenu - article eingestellt und ausgewählt werden.
Wenn man jetzt Beispielsweise in der Seitenstrucktur einen Stamm für die Desktop Webseite hat und einen für die Mobile anlegt, greift immer nur die Desktopversion.

Ist das beabsichtigt?

**Comment by fritzmg** [comment]
Es werden die Artikel eingebunden, die du ausgewählt hast.

In der neuesten Version gibt es dieses Modul in dieser Form nicht mehr. Statt dessen kannst du jetzt einfach HTML Code - oder eben Insert Tags eintragen.
