### ISSUE TITLE
Contao 4: Hauptmenüpunkt wird nicht angezeigt

### ISSUE THREAD

**Issue by rustykowski** [dklemmt/contao_dk_mmenu#20]
Bei Verwendung mit Contao 4 wird im Sliding-off-canvas-Menü der aktuelle Hauptmenüpunkt nicht generiert, wenn es **gleichzeitig der aktive Menüpunkt** ist.
Zuoberst wird vom Script zwar ein li.mm-subtitle mit einem darin enthaltenen a.mm-subclose generiert, dieses Element bleibt aber leer.
Offenbar mag das Script nicht die neuen strong-Elemente in Contaos nav_default-Template. Ersetzt man die strong-Elemente im Template durch span-Elemente (wie in älteren Contao-Versionen), wird das das Sliding-Menü korrekt erzeugt.
Lösungsmöglichkeit 1: Die Erweiterung müsste ein eigenes nav-Template mitliefern.
Lösungsmöglichkeit 2: Das Script müsste so erweitert werden, dass es auch den Inhalt der strong-Elemente erkennt.
![mmenu-problem](https://user-images.githubusercontent.com/1775048/28664385-9ab973bc-72c0-11e7-80cb-3da96d7aec82.png)

**Comment by fritzmg** [comment]
Löst https://github.com/dklemmt/contao_dk_mmenu/pull/15 das Problem?

**Comment by rustykowski** [comment]
Nein, das hatte ich getestet. Mit den CSS-Ergänzungen wird nur die visuelle Hervorhebung verbessert.
Bei dem von mir beschriebenen Problem geht es um unvollständig generiertes Markup.

**Comment by Jaaaan** [comment]
Zu Lösungsmöglichkeit 1:
Es würde als schnelle Lösung reichen, im `nav_default.html5` Template Zeile 4
`<?php if ($item['isActive']): ?>`
zu ersetzen durch
`<?php if (false && $item['isActive']): ?>`.
Der aktive Punkt würde dann aber als Link angezeigt werden.

**Comment by fritzmg** [comment]
Fixed in [`2.0.0`](https://github.com/dklemmt/contao_dk_mmenu/releases/tag/2.0.0)
