### ISSUE TITLE
navbars einfügen?

### ISSUE THREAD

**Issue by operatorone** [dklemmt/contao_dk_mmenu#22]
Ich wollte fragen ob es generell möglich ist in das Menü-Template die "navbars" zu integrieren, da ich einen Header und Footer in dem Menü benötige.

`"navbars": [
                  {
                     "position": "top"
                  },
                  {
                     "position": "bottom",
                     "content": [
                        "<a class='fa fa-envelope' href='#/'></a>",
                        "<a class='fa fa-twitter' href='#/'></a>",
                        "<a class='fa fa-facebook' href='#/'></a>"
                     ]
                  }
               ]
            });`

Viele Grüße,
operatorone

**Comment by fritzmg** [comment]
Mit Version `^3.0@RC` ist dies nun einfacher möglich. Du kannst ein eigenes `js_mmenu` Template anlegen und dort bspw. direkt über PHP `$this->options` und `$this->configuration` ändern.
