### ISSUE TITLE
mmenue 2.0.1, Contao 4.4.18: Inhalt der Seite wird in Schleife geladen

### ISSUE THREAD

**Issue by zonky2** [dklemmt/contao_dk_mmenu#25]
Hi,

habe eine kleine Seite, nur noch Cookiebar und RS-Slider drinn...

wenn ich das das mmenue im Layout aktiviere, wird der Inhalt als Schleife so lange geladen bis die Exec-Time erreicht ist...

Im mmenue sind alles "Standardeinstellungen"

**Comment by fritzmg** [comment]
Verwendest du eigene Templates?

**Comment by zonky2** [comment]
nein...

**Comment by fritzmg** [comment]
Ich denke nicht, dass das etwas direkt mit der Extension oder mmenu zu tun hatte. Versuche aber nichts desto trotz mal die neueste Version ;)
