### ISSUE TITLE
Contao 3.5.35 / dk_mmenu 2.10: Warning: filemtime(): stat failed for jquery.mmenu.fullscreen.css 

### ISSUE THREAD

**Issue by Webstylerin** [dklemmt/contao_dk_mmenu#27]
Hallöchen,

ich habe eine Contao 3.2-Installation auf 3.5 hoch gezogen und dabei auch das dk_mmenu von der legacy-Version auf die aktuelle Composer-Version upgedatet.

Im Frontend gibts jetzt aber immer den Fehler: 

`Warning: filemtime(): stat failed for /www/htdocs/.../websites/layerbylayer.de/system/modules/dk_mmenu/assets/vendor/mmenu/extensions/jquery.mmenu.fullscreen.css in system/modules/core/library/Contao/Controller.php on line 799`

und

`Fatal error: Uncaught exception Exception with message File system/modules/dk_mmenu/assets/vendor/mmenu/extensions/jquery.mmenu.fullscreen.css does not exist thrown in system/modules/core/library/Contao/Combiner.php on line 134`

Die Datei jquery.mmenu.fullscreen.css ist im Modul vorhanden, allerdings im Unterordner "fullscreen". Wenn ich sie dort raus kopiere und direkt unter "extensions" lege, ist der Fehler zwar weg, aber schön ist das ja nicht. :-D

Liegt ein Fehler in der Erweiterung vor oder ist das ein Überbleibsel vom Update? Habe aber sämtliche Caches und auch die beiden Modul-Ordner selbst (in system und in composer) gelöscht und durch den Composer neu runterladen lassen.

LG
Nicole

**Comment by fritzmg** [comment]
Ist ein Fehler in der Extension. Teste mal folgende Änderung: https://github.com/dklemmt/contao_dk_mmenu/commit/6645d74db5f9889e6e00fa3c8c48ad3fb45ecfd7 (_vendor/dklemmt/contao_dk_mmenu/system/modules/dk_mmenu/classes/Mmenu.php_)

**Comment by Webstylerin** [comment]
Fix funktioniert, der Fehler ist weg.

**Comment by fritzmg** [comment]
2.1.1 released
