### ISSUE TITLE
Interne Weiterleitung auf Ankerlink erzeugt nur Anker

### ISSUE THREAD

**Issue by k-webdesign** [dklemmt/contao_dk_mmenu#28]
Contao 4.4.26: Wenn meine Navigation aus internen Weiterleitungen auf einen Anker bestehen, erzeugt die Extension im Frontend nur den Anker, somit funktioniert die Navigation nicht mehr.

<img width="280" alt="screenshot 2018-10-12 09 28 52" src="https://user-images.githubusercontent.com/4130440/46854497-41db9980-ce01-11e8-8e87-f6a8449f5c07.png">

<img width="553" alt="screenshot 2018-10-12 09 29 29" src="https://user-images.githubusercontent.com/4130440/46854518-5750c380-ce01-11e8-8b19-532166a0d393.png">

**Comment by fritzmg** [comment]
Hm, zumindest in der neuesten Version `^3.0@RC` kann ich das nicht nachvollziehen. Bitte ggf. nochmal mit der neuesten Version versuchen.
