### ISSUE TITLE
Kurzes aufleuchten des Menüs verhindern

### ISSUE THREAD

**Issue by akroii** [dklemmt/contao_dk_mmenu#29]
Ich habe auf meiner Seite das mmenu eingebaut. Immer wenn ich eine neue Unterseite aufrufe blinkt das mmenu kurz auf.
Kann man hier etwas dagegen machen? Z.b. per inline css etwas direkt ins Dokument schreiben?

![ezgif-5-53ef7f1a0d61](https://user-images.githubusercontent.com/8830861/53338005-dfdc8600-3902-11e9-9aaf-60df598214d6.gif)

**Comment by fritzmg** [comment]
https://mmenujs.com/support/tips-and-tricks.html » Punkt 3 :)
