### ISSUE TITLE
Open/Close onClick

### ISSUE THREAD

**Issue by jorauch** [dklemmt/contao_dk_mmenu#30]
Ich würde mir eine Option wünschen um das Menü nicht bei :hover sondern onClick öffnet bzw. schließt.

**Comment by fritzmg** [comment]
Das Menü sollte sich nicht bei `:hover` öffnen, sondern nur bei einem click.

**Comment by jorauch** [comment]
Bitte schließt den Changerequest ich hab es im falschen Repo aufgemacht. Ich wollte diesen eigentlich [hier](https://github.com/derhaeuptling/contao-mega-menu) aufmachen. Sorry

**Comment by fritzmg** [comment]
Du kannst selbst dein eigenes Ticket schließen ;)
