### ISSUE TITLE
On-Canvas Option for Contao

### ISSUE THREAD

**Issue by greenskyes** [dklemmt/contao_dk_mmenu#31]
I'm trying to get on work On-Canvas Option for Contao 4.4 mmenu-Plugin. Unfortunately it not works with

```
<script type="text/javascript">
  $(document).ready(function() {
      $("#mmenu").mmenu({
          offCanvas: true;
      });
  });
</script>
```
Do have any idea how to solve this?

**Comment by fritzmg** [comment]
Version `3.0.0@RC` of this extension now uses mmenu `8.1.1+`. Can you please re-describe what you are trying to do and post a link to the documentation of mmenu?

**Comment by fritzmg** [comment]
@greenskyes ist this still relevant?
