### ISSUE TITLE
Umstellung auf mmenu.js - ohne JQuery?

### ISSUE THREAD

**Issue by sebssch** [dklemmt/contao_dk_mmenu#32]
Ist eine Umstellung auf die neue Version mmenu.js ohne JQuery in Planung?
https://mmenujs.com/whats-new.html

**Comment by fritzmg** [comment]
Grundsätzilch würde ich das gern machen - es muss nur finanziert werden.

**Comment by fritzmg** [comment]
See https://github.com/dklemmt/contao_dk_mmenu/pull/33 :)
