### ISSUE TITLE
Erweiterung - Titel konfigurierbar

### ISSUE THREAD

**Issue by mecintosch** [dklemmt/contao_dk_mmenu#34]
Hab die 3.0.0-RC1 unter Contao 4.4 getestet - funktioniert alles wie gewünscht. Einen Vorschlag/Erweiterung zur Konfiguration hätte ich noch...

Den Titel (Standard: Menu) könnte man konfigurierbar und somit (mit Inserttags) mehrsprachig machen. Die Überschrift hat ja hier keinen Sinn, eventuell könnte man dieses Feld nutzen?!

**Comment by fritzmg** [comment]
Hm... andere Felder, wie der Suchplatzhalter, werden über die regulären Übersetzungen gehandhabt. Würde ich dann konsistent damit halten.

**Comment by fritzmg** [comment]
Implemented in b2ba982352d0934f151e37927dbb82d6dc1b8c9c
