### ISSUE TITLE
JS Error in 3.0.0-RC1 - SyntaxError: '#' is not a valid selector

### ISSUE THREAD

**Issue by MacKP** [dklemmt/contao_dk_mmenu#35]
I'm testing the new Version. But i can't figure out why I get the Error: `SyntaxError: '#' is not a valid selector`.
I have testet it in Contao 4.4.40 with and without other JS active.
The error is in line 1 of the code (but there is all Code, so i don't think it is usefull).

Any clue why this could happen?

Kind regards

**Comment by fritzmg** [comment]
You probably did not set a CSS-ID for your mmenu. In its current state it's a mandatory field. I'll see if I can make it optional.

**Comment by MacKP** [comment]
There is an CSS-ID in the Module and I can see the ID in the frontend Code...
When you want to have a look I can give you an Link via slack ^^

Kind regards

**Comment by MacKP** [comment]
Never mind.. It was an update and some Module had no ID. There was the Problem.

Kind regards
