### ISSUE TITLE
mod_mmenu.html5 - invisible Klasse entfernen

### ISSUE THREAD

**Issue by saress** [dklemmt/contao_dk_mmenu#36]
Hallo Fritz,

ich habe heute testweise die neue Version 3 installiert und dabei ist mir aufgefallen,
dass das Menü nach dem Klicken nicht mehr angezeigt wird. Der Grund dafür war auch schnell
gefunden, denn im Template mod_mmenu.html5 findet sich im nav-Container eine invisible CSS-Klasse, die dazu führt, dass das Menü nicht angezeigt wird und die IMHO entfernt werden kann.

Beste Grüße
Sares

**Comment by fritzmg** [comment]
Hm, das war in den früheren Versionen auch bereits im Template, keine Ahnung wieso :). Ich habe nun `invisible` als auch `block` entfernt, damit das Contao CSS Framework möglichst keinen Einfluss auf diese Module haben. Ist schon mit Version 3.0.1 veröffentlicht.

**Comment by saress** [comment]
Vielen Dank für das schnelle Update und ja, genau aus diesem Grund wurde es bei mir dann auch nicht mehr angezeigt :-) Nach dem Update funktioniert jetzt alles wieder.
