### ISSUE TITLE
Springen der Seite beim Einblenden des Menüs

### ISSUE THREAD

**Issue by saress** [dklemmt/contao_dk_mmenu#37]
Hallo Fritz,

mir ist noch aufgefallen, dass das Einblenden der Navigation dazu führt, dass die Scrollbar ausgeblendet wird und die Seiten daher ein wenig "springen", wenn Sie bereits eine Scrollbar haben.

Konkret hängt das vermutlich mit folgender Anweisung zusammen:

`.mm-wrapper_blocking body {
    overflow: hidden;
}`

die beim Öffnen des Menüs greift. 
Ändert man das auf:

`overflow:scroll;` 

verschwindet das Springen. 
Ich hab jetzt aber nicht getestet, ob das irgendwelche anderen Side-Effekte bei Seiten hat, die generell keine Scrollbar haben / brauchen.

Beste Grüße
Sares

**Comment by fritzmg** [comment]
Hm, solche Issues müsstest du hier posten: https://github.com/FrDH/mmenu-js

**Comment by saress** [comment]
OK, danke, ich werde vielleicht zuerst noch schauen, ob das jemand anderem auch schon aufgefallen ist :-)

**Comment by fritzmg** [comment]
Ich kann das auch nachvollziehen. Ist ein typisches Windows Problem. Das Contao back end hat im Prinzip ein verwandtes Problem ;).

Aber die non-Windows User lassen sich dadurch auch schwer überzeugen, dass man das evt. anders machen muss.

**Comment by saress** [comment]
;-)

Ich habe folgendes gefunden:

https://github.com/FrDH/mmenu-js/issues/752

Die Option habe ich jetzt in Deinem Modul auf die Schnelle nicht gefunden und das CSS müsste man dann wohl auch etwas "modifizieren", insgesamt scheint das Problem aber bereits bekannt zu sein.

**Comment by fritzmg** [comment]
Einfach
```css
html.mm-opened #page {
    overflow: auto !important;
}
```
In dein eigenes CSS hinzufügen.

**Comment by saress** [comment]
Danke, ja das hab ich gesehen, werde ich morgen dann gleich mal ausprobieren, irgendwie stört mich das nämlich ein wenig :-)

**Comment by saress** [comment]
Letztendlich hat folgendes funktioniert:

`
.mm-wrapper-blocking body {
  overflow: scroll;
}
`

Wie ich gerade gesehen habe, gibt es auch bereits wieder einen neuen Release 8,2.2. 
Ist Deine Version "angepasst", oder kann man einfach die neue Version einspielen?

Beste Grüße
Sares

**Comment by fritzmg** [comment]
Könntest du prinzipiell einspielen - geht halt beim nächsten Update wieder verloren. Aber das nächste Update wird vielleicht eh wieder die neueste Version enthalten ;)

**Comment by saress** [comment]
Danke Fritz, dann werde ich eher auf Dein Update warten, soweit scheint ja alles was ich brauche zu funktionieren und es ist daher nicht dringend.

**Comment by fritzmg** [comment]
Version 3.0.2 benutzt nun Version 8.2.3 von mmenu. @saress ist dieses Ticket noch relevant?

**Comment by saress** [comment]
Hallo Fritz,

da ich denke, dass das eine individuelle Sache ist, die man einfach selbst lösen kann und die vielleicht nicht jeden stört, kann man das Ticket sicher schließen. 

Danke Fritz und beste Grüße
Sares
