### ISSUE TITLE
Conflict with contao-bootstrap/layout

### ISSUE THREAD

**Issue by cmichael-de** [dklemmt/contao_dk_mmenu#38]
Read more here: https://github.com/contao-bootstrap/layout/issues/12

**Comment by fritzmg** [comment]
I don't quite get the issue. Where is mmenu or contao_dk_mmenu using the `invisible` class?

**Comment by cmichael-de** [comment]
Did you test it in combination with "contao-bootstrap/layout"? You just get the error when using "contao-bootstrap/layout". 

There is no "invisible" class  mod_mmenu.html5 here on github but when I create a new template "mod_mmenu.html5" in my contao project I get:

```
<?php if ($this->type == 'mmenu_article'): ?>
<div class="<?php echo $this->class; ?> invisible block"<?php echo $this->cssID; ?><?php if ($this->style): ?> style="<?php echo $this->style; ?>"<?php endif; ?>>
	<div>

	<?php if ($this->headline): ?>
		<<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
	<?php endif; ?>

		<?php echo implode('', $this->elements); ?>
	</div>
</div>
<?php else: ?>
<!-- indexer::stop -->
	<nav class="<?php echo $this->class; ?> invisible block"<?php echo $this->cssID; ?><?php if ($this->style): ?> style="<?php echo $this->style; ?>"<?php endif; ?>>

	<?php if ($this->headline): ?>
		<<?php echo $this->hl; ?>><?php echo $this->headline; ?></<?php echo $this->hl; ?>>
	<?php endif; ?>

		<a href="<?php echo $this->request; ?>#<?php echo $this->skipId; ?>" class="invisible"><?php echo $this->skipNavigation; ?></a>

		<?php echo $this->items; ?>

		<a id="<?php echo $this->skipId; ?>" class="invisible">&nbsp;</a>

	</nav>
<!-- indexer::continue -->
<?php endif; ?>

```

But David has a good solution posted on https://github.com/contao-bootstrap/layout/issues/12

**Comment by fritzmg** [comment]
> There is no "invisible" class mod_mmenu.html5 here on github but when I create a new template "mod_mmenu.html5" in my contao project I get:

You are not using the latest version of this extension. Those classes have been removed in 3.0.1: https://github.com/dklemmt/contao_dk_mmenu/releases/tag/3.0.1

**Comment by fritzmg** [comment]
@cmichael-de is this still relevant?

**Comment by cmichael-de** [comment]
Sorry for my late reply. You can close the issue.

You are completly right - with version 3.0.1 everything works perfect!
