### ISSUE TITLE
Script Error at Internet Explorer 11 with Version 3.x

### ISSUE THREAD

**Issue by liquid-a** [dklemmt/contao_dk_mmenu#41]
I have a script Error when i usw the mmenu.js with version 3.0.1 or 3.0.2

The console shows: 
**SCRIPT1002: Syntaxfehler
Datei: mmenu.js, Zeile: 1, Spalte: 2278**

The menu is not functional with IE 11. No Problems with Firefox or Chrome.

When i use Verison 2.1.1 everything ist O.K.

**Comment by fritzmg** [comment]
mmenu in general is not compatible with IE 11. There is a PR for automatically including Polyfills though: #40 
I'll release it as 3.1.0 today.

**Comment by Defcon0** [comment]
The problem here is with

```
document.addEventListener(
        "DOMContentLoaded", () => {
            new Mmenu('#<?= $this->elementId ?>', <?= json_encode($this->options) ?>, <?= json_encode($this->configuration) ?>);
        },
    );
```

being the js-template for loading the menu. Why not simply use function() {} instead of () => {} not working in IE11?

**Comment by Defcon0** [comment]
Also the trailing comma leads to a syntax error in IE11. So the more compatible version would be:

```
document.addEventListener(
        "DOMContentLoaded", function() {
            new Mmenu('#<?= $this->elementId ?>', <?= json_encode($this->options) ?>, <?= json_encode($this->configuration) ?>);
        }
    );
```

**Comment by fritzmg** [comment]
Yeah, I can optimize this. Also it was a mistake to call the template `js_mmenu`, as it is not a JavaScript Template that can be included in the page layout.

The code is directly pulled from the documentation of mmenu btw.

**Comment by operatorone** [comment]
Is it already working in IE11. i just implemented the module and activated the polyfill, but the navigation is jut thrown on the page and the trigger doesn't work.

**Comment by fritzmg** [comment]
@operatorone the problems mentioned by @Defcon0 have not been fixed yet.

**Comment by contaoacademy** [comment]
@fritzmg Do you know, when you can fix this?

**Comment by fritzmg** [comment]
@contaoacademy pls create a justom `js_mmenu` template and replace

https://github.com/dklemmt/contao_dk_mmenu/blob/3f49fc0f88be06abb4055a3879010170ffcc04a1/src/Resources/contao/templates/js_mmenu.html5#L15-L19

with:

```javascript
    document.addEventListener(
        "DOMContentLoaded", function() {
            new Mmenu('#<?= $this->elementId ?>', <?= json_encode($this->options) ?>, <?= json_encode($this->configuration) ?>);
        }
    );
```

If this change works, then I'll change it immediately.

**Comment by contaoacademy** [comment]
![error](https://user-images.githubusercontent.com/23719181/70917953-8e7ebe00-201e-11ea-9f66-b4b5ed0fac4d.jpg)
I get this error

**Comment by contaoacademy** [comment]
After using the polyfill option the fix works.

**Comment by fritzmg** [comment]
> @contaoacademy pls create a justom `js_mmenu` template and replace
> 
> https://github.com/dklemmt/contao_dk_mmenu/blob/3f49fc0f88be06abb4055a3879010170ffcc04a1/src/Resources/contao/templates/js_mmenu.html5#L15-L19

https://github.com/dklemmt/contao_dk_mmenu/pull/53
