### ISSUE TITLE
Kurzes aufflackern verhindern

### ISSUE THREAD

**Issue by akroii** [dklemmt/contao_dk_mmenu#44]
Beim laden tritt das mmenu Kurz in Erscheinung (ohne Stylesheets), bevor das Stylesheet greift.

Meine Lösung war es, den Stylesheet inline in den Head zu schreiben:
```
<style>#menu-mobile:not(.mm-menu) {
    display: none;
}
</style>
```
Kann man das nicht auch automatisch machen, da das scheinbar immer (unabhängig von den Einstellungen) auftritt?

Es gibt auch hierzu ähnliche Issues: https://github.com/FrDH/mmenu-js/issues/51

**Comment by fritzmg** [comment]
Duplicate of https://github.com/dklemmt/contao_dk_mmenu/issues/29

**Comment by akroii** [comment]
🤦‍♂️ Its time to take my holiday leave
