### ISSUE TITLE
Also remove `js_mmenu` from page layouts during migration

### ISSUE THREAD

**Issue by fritzmg** [dklemmt/contao_dk_mmenu#46]

**Comment by philvdb** [comment]
Hallo @fritzmg , nur als Feedback: Gerade bei einem Kunden etwas anderes in unserem Bundle geändert und dann nach dem `composer update` von einem harten Crash überrascht worden - `Could not find template "js_mmenu"`. Habe das Template dann notfallmäßig kurzerhand wieder hinzugefügt. Jetzt werde ich versuchen aufzuarbeiten wie es dazu kommen konnte, was die Änderung bezweckt und was ich machen sollte. Anhand deines Commits 2abb53b würde ich ja wenigstens eine neue Zeile im Contao Install tool vermuten, die sich um js_mmenu kümmert, da taucht aber keine auf.

**Comment by fritzmg** [comment]
Wie meinst du eine neue Zeile? Du musst nach dem `composer update` wie gewohnt das Install Tool aufrufen. Dann sollte das Template migriert sein.

Hm, wobei - ihr habt vermutlich einfach das `js_mmenu` im Seitenlayout aktiviert, ohne überhaupt ein eigenes `js_mmenu` template angelegt zu haben. Dieser Fall wird in der Migration derzeit tatsächlich nicht berücksichtigt.

**Comment by fritzmg** [comment]
> was ich machen sollte

Grundsätzlich musst du nur deine Seitenlayouts editieren und nochmals speichern.

**Comment by fritzmg** [comment]
Fixed in 9b908129e12d36f60010b13eb86ba1db3b79d492



> Habe das Template dann notfallmäßig kurzerhand wieder hinzugefügt.

Wenn du nun auf `3.1.2` aktualisierst, musst du dieses Template zuvor wieder löschen und nach dem Update das Install Tool aufrufen. Dann sollte wieder alles passen.

**Comment by philvdb** [comment]
> Hm, wobei - ihr habt vermutlich einfach das js_mmenu im Seitenlayout aktiviert, ohne überhaupt ein eigenes js_mmenu template angelegt zu haben. Dieser Fall wird in der Migration derzeit tatsächlich nicht berücksichtigt.

Ich vermute ganz stark dass du da Recht hast. Der Kunde hat die Erweiterung selbst installiert und ich kenne mich leider gar nicht mit ihr aus.

Ich werde jetzt gerne das Update auf die 3.1.2 vollziehen und berichten, insbesondere wenn es erneut Probleme gibt.

Herzlichen Dank für die unglaublich schnelle Reaktion und ich vermute mit der 3.1.2 hast du dann wahrscheinlich noch andere gerettet ;)

**Comment by philvdb** [comment]
Update auf 3.1.2: request.CRITICAL, js_mmenu not found, nach Aufruf Install Tool behoben. :+1: 

Ich muss zugeben, dass ich bisher nicht die Angewohnheit habe, das Install Tool nach einem composer update laufen zu lassen, außer ich habe selber in einem Bundle ein Datenbankfeld hinzugefügt (was ich dann oft auch erst merke wenn ich das neue Feld im Backend verwenden will ..). Aber kann gut sein dass das nur ich bin und andere das "automatisch" tun - vermute mal sowas übernimmt der Contao Manager z. B., für den bin ich noch zu old school. Aber gut dass wir drüber geredet haben - vielleicht ergooglet das hier ja ein Leidensgenosse: Dann also nach Update auf 3.1.2+ das Install Tool aufrufen!

**Comment by fritzmg** [comment]
> Ich muss zugeben, dass ich bisher nicht die Angewohnheit habe, das Install Tool nach einem composer update laufen zu lassen

Der Contao Manager & die Konsolenausgabe weisen dich aber darauf hin ;)

**Comment by philvdb** [comment]
Echt, wo?

```
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 0 installs, 1 update, 0 removals
  - Updating dklemmt/contao_dk_mmenu (3.1.1 => 3.1.2): Downloading (100%)         
Package oyejorge/less.php is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

                                                                                
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
                                                                                


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

                                                                                
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
                                                                                


 Trying to install assets as relative symbolic links.

 --- -------------------------------------- ------------------ 
      Bundle                                 Method / Error    
 --- -------------------------------------- ------------------ 
  ✔   ContaoCoreBundle                       relative symlink  
  ✔   ContaoFaqBundle                        relative symlink  
  ✔   ContaoNewsBundle                       relative symlink  
  ✔   ContaoNewsletterBundle                 relative symlink  
  ✔   ContaoMmenuBundle                      relative symlink  
  ✔   ContaoCalendarBundle                   relative symlink  
  ✔   ContaoCommentsBundle                   relative symlink  
  ✔   MarkocupicCalendarEventBookingBundle   relative symlink  
  ✔   FlexxBundle                            relative symlink  
 --- -------------------------------------- ------------------ 

                                                                                
 [OK] All assets were successfully installed.                                   
                                                                                

Added the system/initialize.php file.
Symlinked the system/config/tcpdf.php file.

 --- ----------------------------------------------- ---------------------------------------------------------------- 
      Symlink                                         Target / Error                                                  
 --- ----------------------------------------------- ----------------------------------------------------------------
[SNIP]
  ✔   web/files/themes                                files/themes                                                    
  ✔   web/files/tiny_templates                        files/tiny_templates                                            
  ✔   web/system/modules/dcawizard/assets             system/modules/dcawizard/assets                                 
  ✔   web/system/modules/export_table/assets          system/modules/export_table/assets                              
  ✔   web/system/modules/cookiebar/assets             system/modules/cookiebar/assets                                 
  ✔   web/system/modules/notification_center/assets   system/modules/notification_center/assets                       
  ✔   web/system/modules/haste/assets                 system/modules/haste/assets                                     
  ✔   system/themes/flexible                          vendor/contao/core-bundle/src/Resources/contao/themes/flexible  
  ✔   web/assets                                      assets                                                          
  ✔   web/system/themes                               system/themes                                                   
  ✔   system/logs                                     var/logs                                                        
 --- ----------------------------------------------- ----------------------------------------------------------------
```

Das ist der komplette Konsolenoutput von `composer install` bis zum nächsten Prompt.

Den Contao Manager verwende ich wie gesagt nicht - glaube aber natürlich sofort, dass es dort steht. Und man kann sicher auch postulieren, dass Leute die den Manager nicht verwenden, selber wissen sollten, dass es non-BC-breaking Versions-Schritte gibt, die einen Datenbank-Eingriff und damit das Install Tool erfordern. In meinem Fall: Hiermit jetzt gelernt.

**Comment by fritzmg** [comment]
Hm, dürfte wohl nur in neueren Versionen des Manager Bundles so sein.

**Comment by philvdb** [comment]
Alles gut und kein Vorwurf - herzlichen Dank erneut für den schnellen (Gratis-)Support, habe mich von Anfang an nur informativ melden wollen und war durchaus bereit das selber durch zu debuggen. Danke um so mehr für deine Hilfe!
