### ISSUE TITLE
Close button

### ISSUE THREAD

**Issue by Cleanerrr** [dklemmt/contao_dk_mmenu#48]
Hi,
is there any possibility to make a close button into mmenu (such as in the screenshot),
![mmenu-close](https://user-images.githubusercontent.com/30474317/75980904-a6f6ca00-5ee3-11ea-9da9-c4eb038e249c.JPG)

I tried with mmenu mburger (https://mmenujs.com/mburger/tutorial-css.html) but not working.
Maybe can be useful to make an update of Contao mmenu plugin with an implemented field for adding a close button.
Thank you

**Comment by fritzmg** [comment]
Sorry, but this is out of scope for this extension. This Contao extension simply integrates mmenu in Contao and provides modules with settings for it. It does not and will not provide additional features. Any such features would need to be implemented into mmenu itself. However, there are ways to customize mmenu.

**Comment by Cleanerrr** [comment]
Thank you for a very quick answer.
Do you have any hint for customization? 
:)

**Comment by rustykowski** [comment]
I often use the same element, which triggers the menu. You can use the body-class `mm-wrapper_opened`, which is injected, when the menu is opened (as the class-name says). For example: give it a x-symbol as background-image.

**Comment by Cleanerrr** [comment]
Thank you very much :)

**Comment by Cleanerrr** [comment]
> I often use the same element, which triggers the menu. You can use the body-class `mm-wrapper_opened`, which is injected, when the menu is opened (as the class-name says). For example: give it a x-symbol as background-image.

Doy ou have example, maybe?
Thank you in advance

**Comment by rustykowski** [comment]
It is not inside the panel, but here you can see, what i mean:
https://initiative-elmshorn.de/
https://anton-ree-schule-allermoehe.de/

**Comment by Cleanerrr** [comment]
> It is not inside the panel, but here you can see, what i mean:
> https://initiative-elmshorn.de/
> https://anton-ree-schule-allermoehe.de/

Ahaam :)
I understand.
Thank you so much
