### ISSUE TITLE
Funktionsstörung durch Fehler im Template

### ISSUE THREAD

**Issue by redwise** [dklemmt/contao_dk_mmenu#52]
Im Template mod_mmenuHtml.html5 und mod_mmenuCustom.html5 hat sich ein Fehler eingeschlichen.
<nav class="<?= $this->class; ?>"<?= $this->cssID; ?><?php if ($this->style): ?> style="<?= $this->style; ?>"<?php endif; ?> itemscope itemtype="http://schema.org/SiteNavigationElement>

müsste 
<nav class="<?= $this->class; ?>"<?= $this->cssID; ?><?php if ($this->style): ?> style="<?= $this->style; ?>"<?php endif; ?> itemscope itemtype="http://schema.org/SiteNavigationElement">

lauten.

**Comment by fritzmg** [comment]
Dieser Fehle wurde bereits in [`3.1.1`](https://github.com/dklemmt/contao_dk_mmenu/releases/tag/3.1.1) behoben.

**Comment by fritzmg** [comment]
Ah, falsches Template ;)

**Comment by fritzmg** [comment]
Is nun in `3.1.3` behoben.
