### ISSUE TITLE
Where are the css files? - move-Problem  an height first entry

### ISSUE THREAD

**Issue by tsunamitsunami** [dklemmt/contao_dk_mmenu#55]
Dear all,
I just updated from Contao 3.5 to 4.9. Now I got two problms with the site:
1. The contents moves, when using the menu. The cause might me the vanishing scroll bars when clicking the menu.
They came back, wheren closing the menu. Sothe content is moving about halb the width of the scrollbar. I treid overflow:scroll in the body and wrapper class. Nothing happend,

2. The first entry in the menu ha s a smaller height, than the rest. I tried li.active first {height:30px;"} and span.active first{height:35px;}
without success. To see any effekt, I tried a simple color:red to the classes. Nothing happend.So there must be an extra css file beeing loaded. When analysing the source with chrome I saw an entry like 400px x 20px, Where is this defined?

How can I fix this. Thanx  4 hints
tsunami

**Comment by fritzmg** [comment]
> Where are the css files?

https://github.com/dklemmt/contao_dk_mmenu/tree/master/src/Resources/public/mmenu

Regarding your troubles: this is unlikely caused by the extension itself. May be you should ask in the Contao community forum for help.

**Comment by tsunamitsunami** [comment]
Waow, that was fast. Thanx!
Sorry, I didn't mean the download source, but the structure of the
installation. The past, there was s th like system/modules/mmenu/css...
But this folder is empty.
Yes I ill as in the cc,
Regards
tsunami

Am Mi., 22. Juli 2020 um 11:20 Uhr schrieb Fritz Michael Gschwantner <
notifications@github.com>:

**Comment by fritzmg** [comment]
Composer installs packages into the `vendor/` folder of your project. For this package it would be `vendor/dklemmt/contao_dk_mmenu`. But why do you need to know that? You cannot change anything there anyway, as the changes will get lost.

**Comment by tsunamitsunami** [comment]
Arn't there any css.-files, within I could solve my problems?

Am Mi., 22. Juli 2020 um 11:36 Uhr schrieb Fritz Michael Gschwantner <
notifications@github.com>:

**Comment by fritzmg** [comment]
@tsunamitsunami you need to create your own CSS files with styles that override any of the modules styles - and include them in your layout.
