### ISSUE TITLE
Conflict - lätzte Contao 4.11

### ISSUE THREAD

**Issue by Cleanerrr** [dklemmt/contao_dk_mmenu#60]
`[6.9MiB/0.24s] Loading composer repositories with package information
[54.7MiB/1.56s] Updating dependencies
[1100.4MiB/7.60s] Your requirements could not be resolved to an installable set of packages.
[1100.4MiB/7.61s] 
  Problem 1
    - dklemmt/contao_dk_mmenu[3.2.0, ..., 3.2.2] require symfony/dependency-injection ^3.4 || ^4.0 -> satisfiable by symfony/dependency-injection[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.19].
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.19.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.18.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.17.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.16.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.15.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.14.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.13.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.12.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.4.0.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.3.0.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.12.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.2.0.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.12.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.1.0.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.15.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.14.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.13.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.12.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v4.0.0.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.47.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.46.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.45.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.44.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.43.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.42.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.41.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.40.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.39.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.38.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.37.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.36.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.35.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.34.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.33.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.32.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.31.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.30.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.29.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.28.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.27.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.26.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.25.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.24.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.23.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.22.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.21.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.20.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.19.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.18.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.17.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.16.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.15.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.14.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.13.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.12.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.11.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.10.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.9.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.8.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.7.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.6.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.5.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.4.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.3.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.2.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.1.
    - symfony/web-profiler-bundle v5.2.3 conflicts with symfony/dependency-injection v3.4.0.
    - contao/manager-bundle 4.11.0 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.3].
    - contao/manager-bundle is locked to version 4.11.0 and an update of this package was not requested.
    - Root composer.json requires dklemmt/contao_dk_mmenu ^3.2 -> satisfiable by dklemmt/contao_dk_mmenu[3.2.0, 3.2.1, 3.2.2].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
[1100.5MiB/7.61s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[44.2MiB/8.60s] Memory usage: 44.19MB (peak: 1101.4MB), time: 8.61s.`

**Comment by fritzmg** [comment]
Please use three back ticks to post code, console output etc.

**Comment by fritzmg** [comment]
Please try version `3.2.3`.

**Comment by Cleanerrr** [comment]
Seems like a problem/conflict with the Page image module. 
I uninstalled the Page image, and the "mmenu" working normal, but the Page image has some problems.

**Comment by fritzmg** [comment]
You will likely need to run a full package update after adding the extension.
