### ISSUE TITLE
hammer.js sourcemap

### ISSUE THREAD

**Issue by marcobiedermann** [dklemmt/contao_dk_mmenu#7]
Hammer.js SourceMap is not available.
`GET http://website.de/assets/js/hammer.min.map 404 (Not Found)`
I suggest to remove the last line in [`assets/js/hammer.min.js`](https://github.com/dklemmt/contao_dk_mmenu/blob/master/system/modules/dk_mmenu/assets/js/hammer.min.js#L7)

**Comment by fritzmg** [comment]
This does not exist anymore.
