### ISSUE TITLE
Make compatible with PHP 8.1 and CONTAO 5

### ISSUE THREAD

**Issue by erikherbert** [dklemmt/contao_dk_mmenu#71]
Please, can you make it compatible with PHP 8.1 and CONTAO 5

**Comment by rabauss** [comment]
PHP 8.1 is already unlocked - for contao 5 you may support a developer 💸

**Comment by erikherbert** [comment]
We had pushed you a working solution! ;-)

**Comment by rabauss** [comment]
@erikherbert I don't understand - where is the working solution? 🤔

**Comment by rabauss** [comment]
@d0p3fish Attention I solved some errors in the master branch with #66
Maybe you could rebase your fork when #66 is finally merged ☺️ 
I think your changes should be compatible with contao 4.13, shouldn't they?

**Comment by rorych** [comment]
Is the recommended solution to use https://github.com/saxony-switzerland-developers/contao_dk_mmenu or will the original repo also be compatible with contao 5?

**Comment by fritzmg** [comment]
https://github.com/saxony-switzerland-developers can provide a PR for this repository.

**Comment by fritzmg** [comment]
Contao 5 compatibility released with `4.1.0` (6cc8509fc718293cb208e2e933ca7366aedfad75).
