### ISSUE TITLE
fixed elements

### ISSUE THREAD

**Issue by Messa1** [dklemmt/contao_dk_mmenu#8]
Super wäre wenn die AddOns auch verwendet werden könnten ;)
http://mmenu.frebsite.nl/documentation/addons/fixed-elements.html
Eventuell eine Checkbox im Backend und ein Textfeld um die Klassen einzutragen.

Ok. Du hast die AddOns mit gegeben :+1: 
Zwar die alte Version. Aber klappt alles.

**Comment by dklemmt** [comment]
Ja alles was im Contao-BE konfiguriert werden kann ist dabei. Habe nur aktuell überhaupt keine Zeit bzw. nachdem ich den ganzen Tag schon Frontend-Entwicklung mache, das abends noch weiter zu machen. Daher wird es noch etwas dauern bis ich die ganz neue Version unterstützte. Da Fred sehr viel geändert hat, muß ich leider ebenso viel anpassen. :(

**Comment by leonid22** [comment]
Kann man denn das "fixed-elements AddOn" überhaupt in contao verwenden? Ich habe das mal manuell ins Template geladen, muss aber das fixed div (#header mit scrollTofixed übrigens) mit ".FixedTop" statt mit ".Fixed" versehen, damit es angesprochen wird (vermutlich weil es eine frühere Version des AddOns ist..) und trotzdem verschwindet der #header (oder landet am Fuß der der Seite) wenn ich das mmenu aufrufe. Wär halt schon schön wenn der #header oben trotz Menü sichtbar bleibt. 
Abschließend noch vielen Dank für die Contao-Umsetzung!

**Comment by nrunde** [comment]
@leonid22 Hast du dafür vielleicht bereits eine Lösung gefunden? Habe gerade das gleiche Problem.

**Comment by leonid22** [comment]
@nrunde ...leider (noch) nicht. Ich werde mich dem am Wochenende nochmal widmen. Melde mich falls es dann klappt.

**Comment by dklemmt** [comment]
Prinzipiell ist das Script auch manuell nicht weiter schwer einzubinden. Die Erweiterung nimmt einem nur eben diese Arbeit ab. Aber wenn man die einzelnen Scripts und den mmenu-Aufruf mit den Parametern im Layout hinzufügt sollte das recht problemlos gehen.

Die Lizenz hat sich aber leider mit dem letzten Release geändert. Ist nun nicht mehr MIT.

**Comment by fritzmg** [comment]
In der neuesten Version steuert man dies nun mit CSS Klassen.
