### ISSUE TITLE
Problems with Contao version 5.3.x and dk_mmenu 4.1.2 / position:fix no longer works because of transform: translate3d(0,0,0);

### ISSUE THREAD

**Issue by d003232** [dklemmt/contao_dk_mmenu#80]
In Contao 5.x the positioning of elements with position:fix does not work anymore. The cause seems to be the use of:
.mm-wrapper--position-left .mm-slideout, .mm-wrapper--position-right .mm-slideout
-webkit-transform: translate3d(0,0,0);
  transform: translate3d(0,0,0);
}

Due to the CSS property transform, position:fix no longer recognises the viewport correctly.

**Comment by fritzmg** [comment]
This is unrelated to Contao 5.

**Comment by fritzmg** [comment]
And in any case, this is a pure CSS issue which this extension cannot do anything about. This extension just helps you integrate [mmenu.js](https://mmenujs.com/), nothing more.
