### ISSUE TITLE
dkmenu möchte Datei ".css" includen

### ISSUE THREAD

**Issue by akroii** [dklemmt/contao_dk_mmenu#9]
Ich habe versucht Composer in meine Contao-Installation einzubauen. Direkt nachdem ich Composer installiert habe (+ Migration aller Plugins) habe ich diese Fehlermeldung erhalten:

```
[01-Dec-2015 10:08:16 Europe/Berlin] 
PHP Warning: filemtime(): stat failed for C:\xampp\htdocs\yyy/system/modules/dk_mmenu/assets/css/themes/.css in C:\xampp\htdocs\yyy\system\modules\core\library\Contao\Controller.php on line 793
#0 [internal function]: __error(2, 'filemtime(): st...', 'C:\\xampp\\htdocs...', 793, Array)
#1 C:\xampp\htdocs\yyy\system\modules\core\library\Contao\Controller.php(793): filemtime('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\yyy\system\modules\core\classes\FrontendTemplate.php(102): Contao\Controller::replaceDynamicScriptTags('<!DOCTYPE html>...')
#3 C:\xampp\htdocs\yyy\system\modules\core\pages\PageRegular.php(190): Contao\FrontendTemplate->output(true)
#4 C:\xampp\htdocs\yyy\system\modules\core\controllers\FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 C:\xampp\htdocs\yyy\index.php(20): Contao\FrontendIndex->run()
#6 {main}
```

Die Datei ".css" existiert nicht indem Ordner Assets. Wenn ich diese Datei anlege verschwindet diese Fehlermeldung.

Contao 3.5.4
dk_menu 1.5.1.9007

**Comment by Ilford125** [comment]
Having the same problem with contao version 3.5.12 and dk_mmenu version 1.5.1 build 7.
Any solutions baking in the oven?

**Comment by Ilford125** [comment]
Die Lösung ist der Wechsel des Themes. dk_mmenu sucht nach einen theme, das es nicht findet. Wechselt im Modul mal das theme.

Siehe contao-forum:
[https://community.contao.org/de/showthread.php?50942-dk_mmenu-Fatal-Error&p=408796#post408796](url)

**Comment by fritzmg** [comment]
Sollte nicht mehr auftreten. Falls doch, bitte hier nochmal reporten.
